remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme

title: Roberto Stagi

description: >
  Some awesom description about Roberto Stagi.

baseurl: "/"
url: "http://rstagi.github.io"
github_username: "rstagi"

markdown: kramdown
permalink: /:year/:title:output_ext


