remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme

title: Roberto Stagi

description: >
  Full Stack Engineer & Innovation Enthusiast.

baseurl: "/"
url: "http://rstagi.github.io"
github_username: "rstagi"
email: "me@rstagi.com"

markdown: kramdown
permalink: /:year/:title:output_ext


